### PR TITLE
Week2 working

### PR DESCRIPTION
**Pull request by helo12**
Ok Everything is implemented I am just struggling with the creating an admin account. Other than that this is ready for review. In the current state it is currently the create admin account in start up is uncommented and will cause an error. See the attached screen shot. 

image

### CODE REVIEW

**Review by cassidykane — COMMENTED** [review]
Okay, here are the issues I found:

When the NavBar on the top collapses with window resizing, it starts to overlap the content beneath it.

Customers and Users created in the Admin/Create don't show up in CustomerView or Admin/Index. 

I was able to submit a message without putting any input in the fields. It showed up in MessageView with no values. 

When I submit a message, it shows up in MessageView with the info I entered. But Navigating away from the page and back again shows it with Name, Email, Address and City values changed to "Blank", "Blank@gmail.com", "3946 Blank drive" and "Blank", with only the "bugOrError" checkbox selected. However, navigating to Home/CustomerView after that shows me customers generated with the original customer info I had entered in the MessageForm.

Deleting a customer or sent message (using the button in the table row) returns this error:
deletesent

The search bar in MessageView doesn't do anything. The search bar in CustomerView properly returns results when I enter an existing name. However, when I search for something that isn't there, it displays a result for a customer with no values in its fields.   

As for the problem The thing that made CreateAdminAccount work for me was passing my User model in IdentityDbContext where AppDbContext inherits from it. So for you it would be 

`AppDbContext : IdentityDbContext<Customer>`

Hope this helps! Brian's code doesn't use this, but the example from the textbook does. So I'm not sure why it was the thing that made it work for me.

**Comment by helo12** [comment]
So implemented the  AppDbContext : IdentityDbContext<Customer> and did not change the error unfortunately

**Comment by helo12** [comment]
So no idea why but it is working I am having some view issues but the login functionality is complete.

**Comment by helo12** [comment]
Well now what I am having issues with is making sure that a view requires authentication in order to be viewed. It all  looks very similar to what is going on in book info but for some reason its just not lining up correctly. However the making of the admin user and the act of logging in is working successfully

**Comment by helo12** [comment]
Ok Everything is working to within a marginal degree. There are some styling things that need to be fixed but login logout now works, account creation now works, role listing, and partially role editing now works, page by page authorization for roles now works. As such I am closing this pull request

**Pull request merged**
